<?xml version="1.0"?>
<root xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
  
  <include filename="$(find raw_description)/urdf/sensors/asus_xtion.gazebo.xacro" />
  
  <property name="eye_radius" value="0.0095" />
  <property name="eye_length" value="0.002" />
  <property name="eye_x_offset" value="0.025" />
  <property name="eye_y_offset" value="0.035" />
  
  <xacro:macro name="asus_xtion_eye" params="suffix parent *origin">
		<link name="${parent}_${suffix}_link">
			<inertial>
				<mass value="1" />
				<origin xyz="0 0 0" />
				<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
			</inertial>
			
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
		        <geometry>
		          	<cylinder length="${eye_length}" radius="${eye_radius}"/>
		        </geometry>
		        <material name="Blue" />
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
		        <geometry>
		          	<cylinder length="${eye_length}" radius="${eye_radius}"/>
		        </geometry>
			</collision>
		</link>
		
		<joint name="${parent}_${suffix}_joint" type="fixed">
			<parent link="${parent}_camera"/>
			<child link="${parent}_${suffix}_link"/>
			<insert_block name="origin"/>

		</joint>		
	</xacro:macro>
    

  <xacro:macro name="asus_xtion" params="name parent *origin ros_topic tilt">
  	<link name="${name}_foot_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.088 0.005"/>
        </geometry>
        <material name="Red" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
           <box size="0.05 0.088 0.005"/>
        </geometry>
      </collision >
    </link>
    
    <joint name="${name}_foot_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_foot_link"/>
    </joint>
  
    
    <link name="asus_xtion_tilt_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz="0 0 0.0075" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.025" radius="0.005" />
        </geometry>
        <material name="Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0.0075" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.025" radius="0.005" />
        </geometry>
        <material name="Blue" />
      </collision >
    </link>
    
    <joint name="asus_xtion_tilt_joint" type="fixed">
     	<parent link="${name}_foot_link"/>
     	<child link="asus_xtion_tilt_link"/>
     	<!--<axis xyz="0 1 0"/>-->
      	<origin xyz="0 0 0.0075" rpy="0 ${tilt} 0"/>
	<!--<limit effort="100" lower="-0.541052068" upper="0.541052068" velocity="1.0"/>-->
    </joint>
    
    
    <link name="${name}_camera">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz="0 -0.03 0" rpy="0 0 0" />
        <geometry>
          <box size="0.05 0.18 0.035"/>
        </geometry>
        <material name="Red" />
      </visual>

      <collision>
        <origin xyz="0 -0.03 0" rpy="0 0 0" />
        <geometry>
           <box size="0.05 0.18 0.035"/>
        </geometry>
      </collision >
    </link>
    
    <joint name="${name}_camera_joint" type="fixed">
      <origin xyz="0 0.03 0.03" rpy="0 0 0" />
      <parent link="asus_xtion_tilt_link"/>
      <child link="${name}_camera"/>
    </joint>
    
        
	<xacro:asus_xtion_eye suffix="depth_camera" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.02} 0" rpy="0 ${M_PI/2} 0" />
	</xacro:asus_xtion_eye>
	
	<xacro:asus_xtion_eye suffix="rgb_camera" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.04} 0" rpy="0 ${M_PI/2} 0" />
	</xacro:asus_xtion_eye>
	
	<xacro:asus_xtion_eye suffix="laser" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.09} 0" rpy="0 ${M_PI/2} 0" />
	</xacro:asus_xtion_eye>

    
   <!-- for simulation -->
   <xacro:asus_xtion_gazebo name="${name}" ros_topic="${ros_topic}"/>

  </xacro:macro>

</root>
