global_costmap:
    publish_voxel_map: false
    global_frame: map
    robot_base_frame: base_footprint
    update_frequency: 2.5
    publish_frequency: 1.0
    static_map: true
    rolling_window: false
 
