# Robot Configuration Parameters
acc_lim_x: 0.7
acc_lim_y: 0.7
acc_lim_th: 0.7
max_vel_x: 0.1
min_vel_x: 0.01
max_rotational_vel: 0.1
min_in_place_rotational_vel: 0.01
escape_vel: -0.1
holonomic_robot: true

# Goal Tolerance Parameters
xy_goal_tolerance: 0.1
yaw_goal_tolerance: 0.1

# Forward Simulation Parameters
sim_time: 1.7
sim_granularity: 0.025
vx_samples: 20
vtheta_samples: 20

# Trajectory Scoring Parameters
goal_distance_bias: 0.8
path_distance_bias: 1.6
occdist_scale: 0.01
heading_lookahead: 0.325
dwa: true

# Oscillation Prevention Parameters
oscillation_reset_dist: 0.01

