# goal
geometry_msgs/PoseStamped goal
float64[] cartesian_stiffness
float64[] cartesian_damping
---
# result
arm_navigation_msgs/ArmNavigationErrorCodes result
---
# feedback
arm_navigation_msgs/ArmNavigationErrorCodes result
