#!/usr/bin/python
import roslib; roslib.load_manifest('raw_open_challenge_iros2012')
import rospy

import smach
import smach_ros

from simple_script_server import *
sss = simple_script_server()

class point_to_recognized_objects(smach.State):

    def __init__(self):
        smach.State.__init__(self, outcomes=['succeeded', 'failed'], input_keys=['object_list', 'recognized_objects'])
        count_recognized = 0
        #ToDo set path relative to the working directory
        sss.set_wav_path("/home/jose/atwork/RoboCupAtWork/raw_scenarios/iros_2012/raw_open_challenge_iros2012")
        
    def execute(self, userdata):
       #sss.move("gripper", "open", blocking=False)
       #sss.move("arm", "zeroposition")
       global planning_mode
       sss.move("arm", "zeroposition", mode=planning_mode) 
 
        for object in userdata.recognized_objects:         
            
            # ToDo: need to be adjusted to correct stuff           
            if object.pose.pose.position.z <= 0.0 or object.pose.pose.position.z >= 0.10:
                continue
    
            #object.pose.pose.position.z = object.pose.pose.position.z + 0.02
            object.pose.pose.position.x = object.pose.pose.position.x + 0.01
            object.pose.pose.position.y = object.pose.pose.position.y - 0.005

            #ToDo Check the 'pregrasp' position to point the object
            handle_arm = sss.move("arm", [object.pose.pose.position.x, object.pose.pose.position.y, object.pose.pose.position.z, "/base_link"], mode=planning_mode)

            if handle_arm.get_state() == 3:
                #sss.move("gripper", "close", blocking=False)
                #ToDo complete the sss.play with the objects names from recognized_objects and add .wav files to the directory
                #The .wav file can be generated by using festival
                #text2wave -o output.wav text.to.speak.txt
                #sss.play takes as input the name of the .wav file to play, the .wav file should be in the /common/files/en directory 
                #sss.play(object.name)
                rospy.sleep(3.0)
                sss.move("arm", "zeroposition", mode=planning_mode)
                count_recognized = count_recognized + 1
                if (count_recognized >= len(userdata.recognized_objects)):        
                  return 'succeeded'    
            else:
                rospy.logerr('could not find IK for current object')

        return 'failed'


