<?xml version="1.0"?>
<root xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">


  <include filename="$(find raw_description)/urdf/sensors/kinect.urdf.xacro" />

  <property name="height" value="0.515" />
  <property name="width" value="0.03" />
  <property name="depth" value="0.03" />
  
  <xacro:macro name="cam3d_tower" params="name parent *origin">
  	<link name="${name}_link">
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 ${(height/2) - height}" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz="0 0 ${height - (height/2)}" rpy="0 0 0" />
        <geometry>
          <box size="${depth} ${width} ${height}"/>
        </geometry>
        <material name="LightGrey" />
      </visual>

      <collision>
        <origin xyz="0 0 ${height - (height/2)}" rpy="0 0 0" />
        <geometry>
           <box size="${depth} ${width} ${height}"/>
        </geometry>
      </collision >
    </link>
    
    <joint name="${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
  </xacro:macro>

  <!-- 3D camera on tower -->
  <xacro:kinect name="openni" parent="tower_link" ros_topic="/camera/rgb/points" tilt="0.61">
    <origin xyz="0 -0.04 ${height-0.05}" rpy="0 0 0" />
  </xacro:kinect>

</root>
