# Robot Configuration Parameters
acc_lim_x: 0.7
acc_lim_y: 0.7
acc_lim_th: 0.7
max_vel_x: 0.3
min_vel_x: 0.05
max_rotational_vel: 0.5
min_in_place_rotational_vel: 0.04
escape_vel: -0.1
holonomic_robot: true

# Goal Tolerance Parameters
xy_goal_tolerance: 0.1
yaw_goal_tolerance: 0.1

# Forward Simulation Parameters
sim_time: 1.3
sim_granularity: 0.025

goal_distance_bias: 32.0
path_distance_bias: 24.0
occdist_scale: 0.01
heading_lookahead: 0.325
dwa: false

stop_time_buffer: 0.2
oscillation_reset_dist: 0.05

forward_point_distance: 0.325

scaling_speed: 0.25
max_scaling_factor: 0.2

vx_samples: 3
vy_samples: 10
vtheta_samples: 20

sim_period: 0.1

xy_goal_tolerance: 0.2
yaw_goal_tolerance: 0.17

rot_stopped_vel: 0.01
trans_stopped_vel: 0.01

penalize_negative_x: false
