global_costmap:
    publish_voxel_map: false
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 0.1
    publish_frequency: 0.0
    static_map: true
    rolling_window: false
    width: 5.0
    height: 5.0
    resolution: 0.05
    origin_x: 0.0
    origin_y: 0.0
