#BEGIN VOXEL STUFF
#map_type: voxel
map_type: costmap
origin_z: 0.0
z_voxels: 16
z_resolution: 0.1125
unknown_cost_value: 0
unknown_threshold: 8
mark_threshold: 0
#END VOXEL STUFF

transform_tolerance: 0.4
obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.25

observation_sources: laser_scanner_front,laser_scanner_rear

laser_scanner_front: {sensor_frame: base_laser_front_link, data_type: LaserScan, topic: /scan_front, expected_update_rate: 0.2, observation_persistence: 0.0,  marking: true, clearing: true, min_obstacle_height: -0.10, max_obstacle_height: 2.0}
