acc_lim_th: 1.0
acc_lim_x: 1.0
acc_lim_y: 1.0

max_vel_x: 0.2
min_vel_x: -0.1

max_vel_y: 0.2
min_vel_y: -0.2

max_trans_vel: 0.2
min_trans_vel: 0.01

max_rot_vel: 0.4
min_rot_vel: -0.4

sim_time: 3.0
sim_granularity: 0.08

goal_distance_bias: 32.0
path_distance_bias: 24.0
occdist_scale: 0.01

stop_time_buffer: 0.2
oscillation_reset_dist: 0.05

forward_point_distance: 0.08

scaling_speed: 1.0
max_scaling_factor: 1.0

vx_samples: 3
vy_samples: 10
vtheta_samples: 20

sim_period: 0.1

xy_goal_tolerance: 0.1
yaw_goal_tolerance: 0.5

rot_stopped_vel: 0.01
trans_stopped_vel: 0.01

controller_frequency: 10
penalize_negative_x: false
