# eband local planner parameters

#connectivity checking
eband_min_relative_bubble_overlap_ : 0.7

#bubble geometric bounds
eband_tiny_bubble_distance: 0.01
eband_tiny_bubble_expansion: 0.01

#optimization - force calculation
eband_internal_force_gain: 0.4
eband_external_force_gain: 0.9
num_iterations_eband_optimization: 3

#recursive approximation of bubble equilibrium position based
eband_equilibrium_approx_max_recursion_depth: 4
eband_equilibrium_relative_overshoot: 0.75
eband_significant_force_lower_bound: 0.15

# eband_trajectory_controller parameters
max_vel_lin: 0.4
max_vel_th: 1.5

min_vel_lin: 0.1
min_vel_th: 0.0

min_in_place_vel_th: 0.0
in_place_trans_vel: 0.0

tolerance_trans: 0.02
tolerance_rot: 0.04
tolerance_timeout: 0.5

k_prop: 4.0
k_damp: 3.5
Ctrl_Rate: 10.0

max_acceleration: 1.0
virtual_mass: 0.75

max_translational_acceleration: 0.5
max_rotational_acceleration: 1.5

rotation_correction_threshold: 0.5
