#Independent settings for the local planner's costmap. Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d

local_costmap:

  #Set the global and robot frames for the costmap
  global_frame: /odom
  robot_base_frame: base_footprint

  #Set the update and publish frequency of the costmap
  update_frequency: 5.0
  publish_frequency: 0.0

  #We'll configure this costmap to be a rolling window... meaning it is always
  #centered at the robot
  static_map: true
  rolling_window: false
  width: 10.0
  height: 6.0
  resolution: 0.04
  origin_x: 0.0
  origin_y: 0.0

  # set the local costmap to allow trespassion of unknown space
  track_unknown_space: true
  unknown_threshold: 10 #9 #values >9 let costmap treat unknown space as free
